spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:5722/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
#    json返回时,忽略为null的字段
    default-property-inclusion: non_null
server:
  context-path: /sell
  
wechat:
#  公众号AppId
  mpAppId: wx7029de18a88b409b
  mpAppSecret: 7de357dc867219daadb60c588dbe4a72
