spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.102.15:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #格式化SQL语句
    properties:
      hibernate.format_sql: true
server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: E:/log/tomcat/sell.log
#  level:
#    com.imooc.sell.LoggerTest: debug