spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #格式化SQL语句
    properties:
      hibernate.format_sql: true
  jackson:
    #json返回值属性中不包含null的属性值
    default-property-inclusion: non_empty
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
#server:
#  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: E:/log/tomcat/sell.log
#  level:
#    com.imooc.sell.LoggerTest: debug

#微信公众号Id和Secret配置
wechat:
  #公众号appId
  mpAppId: wxd898fcb01713c658
  #公众号appSecret
  mpAppSecret: xxxxxxxxxx
  #商户号
  mchId: 1483469312
  #商户密钥
  mchKey: C5245D70627C1F8E9964D494B0735025
  #商户证书路径
  keyPath: E:/JavaDev/weixin_cert/h5.p12
  #微信支付异步通知地址
  notifyUrl: http://xsell.natapp1.cc/pay/notify